  apiVersion: networking.gke.io/v1
  kind: ManagedCertificate
  metadata:
    name: teolia-devops-cert
  spec:
    domains:
      - teolia-school-devops.fr

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    networking.gke.io/managed-certificates: "teolia-devops-cert"
spec:
  rules:
  - host: teolia-school-devops.fr
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-lb-service
            port:
              number: 80