## DOC LINK: https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
  namespace: app
spec:
  domains:
    - dockercoins.teolia-school-devops.fr

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nginx-backend
  namespace: app
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /index.html
    port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-backend-ingress-backend-config
  namespace: app
  labels:
    app: nginx-backend-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"nginx-backend"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: nginx
  type: NodePort  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managed-cert-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ingress-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: nginx-backend-ingress-backend-config
      port:
        number: 80