kind: Service
apiVersion: v1
metadata:
  name: webui-service
  namespace: app
spec:
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 1024
    targetPort: 1024

---    

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: app
  labels:
    app: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: web
        image: __GAR_LOCATION__-docker.pkg.dev/__PROJECT_NAME__/__REPOSITORY__/webui:__TAG__
        ports:
        - containerPort: 1024
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
      nodeSelector:
        app: second

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-autoscaler
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100