name: Curation workflow
run-name: Curation workflow
on: push # Will be changed to schedule trigger depending on the chosen policy
# It will be: if pull_request == closed then process to eliminate all intermediate images with github-sha in their tag
#   pull_request:
#        cloesd
env:
    GAR_LOCATION: europe-west1
    REGISTRY: teolia-school-devops
    REPOSITORY: teolia-school-amineb
jobs:
    CleanUpDockerImages:
        name: Clean up Docker Images
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: 'Login to Google Artifacts Registry'
              uses: "./.github/template/login-docker" 
              with:
                gcloud_key: ${{ secrets.GLOUD_KEY }}
                gar_location: ${{ env.GAR_LOCATION }}

            - id: release
              run: |
                currentVersion=$(cat VERSION)
                echo "currentVersion=$(cat VERSION)" >> $GITHUB_OUTPUT

            - name: 'Remove webui intermediate images'
              uses: "./.github/template/curation" 
              with:
                image_name: "webui"
                location: ${{ env.GAR_LOCATION }}
                registry: ${{ env.REGISTRY }}
                repository: ${{ env.REPOSITORY }}
                version: ${{ steps.release.outputs.currentVersion }}
            
            - name: 'Remove nginx intermediate images'
              uses: "./.github/template/curation" 
              with:
                image_name: "nginx"
                location: ${{ env.GAR_LOCATION }}
                registry: ${{ env.REGISTRY }}
                repository: ${{ env.REPOSITORY }}
                version: ${{ steps.release.outputs.currentVersion }} 
            
            - name: 'Remove nginx-test intermediate images'
              uses: "./.github/template/curation" 
              with:
                image_name: "nginx-test"
                location: ${{ env.GAR_LOCATION }}
                registry: ${{ env.REGISTRY }}
                repository: ${{ env.REPOSITORY }}
                version: ${{ steps.release.outputs.currentVersion }}
                
            - name: 'Remove rng intermediate images'
              uses: "./.github/template/curation" 
              with:
                image_name: "rng"
                location: ${{ env.GAR_LOCATION }}
                registry: ${{ env.REGISTRY }}
                repository: ${{ env.REPOSITORY }}
                version: ${{ steps.release.outputs.currentVersion }}
                
            - name: 'Remove hasher intermediate images'
              uses: "./.github/template/curation" 
              with:
                image_name: "hasher"
                location: ${{ env.GAR_LOCATION }}
                registry: ${{ env.REGISTRY }}
                repository: ${{ env.REPOSITORY }}
                version: ${{ steps.release.outputs.currentVersion }}
            
            - name: 'Remove worker intermediate images'
              uses: "./.github/template/curation" 
              with:
                image_name: "hasher"
                location: ${{ env.GAR_LOCATION }}
                registry: ${{ env.REGISTRY }}
                repository: ${{ env.REPOSITORY }}
                version: ${{ steps.release.outputs.currentVersion }}    
